name: fetch-prices
on:
  schedule:
    - cron: '3 12,13,14,15 * * *'
    - cron: '34 14,15,16,17,18 * * *'
jobs:
  build:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Curl
        run: |
          curl --fail \
          --request POST \
          --url 'https://tuntihinta-tallentaja.vercel.app/api/' \
          --header "Authorization: Bearer ${{ secrets.TH_REQUEST_TOKEN }}"
